name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release (optional)
        required: false
      force:
        description: Force a release even when there are release-blockers (optional)
        required: false
  schedule:
    - cron: "0 18 15 * *"
jobs:
  release:
    if: github.repository_owner == 'codecov'
    permissions:
      pull-requests: 'write'
      contents: 'read'
    runs-on: ubuntu-latest
    name: "Release a new version"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Prepare release
        id: prepare-release
        uses: getsentry/action-prepare-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: ${{ github.event.inputs.version }}
          force: ${{ github.event.inputs.force }}
          calver: true
    outputs:
      release-version: ${{ env.RELEASE_VERSION }}